version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: contabilidade_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: contabilidade_seaweedfs
    restart: always
    ports:
      - "9333:9333"
      - "8080:8080"
      - "8333:8333"
    volumes:
      - seaweedfs_data:/data
    command: server -dir=/data -s3
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://localhost:9333/cluster/status",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contabilidade_front
    restart: always
    ports:
      - "3000:3000"

    depends_on:
      postgres:
        condition: service_healthy
      seaweedfs:
        condition: service_healthy

    environment:
      NODE_ENV: ${NODE_ENV}
      PRETTY_LOG: ${PRETTY_LOG}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      AES_SECRET: ${AES_SECRET}
      JWT_SECRET: ${JWT_SECRET}

      # SeaweedFS
      SEAWEEDFS_URL: ${SEAWEEDFS_URL}
      SEAWEEDFS_S3_URL: ${SEAWEEDFS_S3_URL}
      AWS_ACCESS_KEY_ID: ${SEAWEEDFS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${SEAWEEDFS_SECRET_KEY}

    command: sh -c "
      npx prisma@5.22.0 migrate deploy &&
      npx prisma@5.22.0 db seed &&
      node server.js
      "

volumes:
  pgdata:
  seaweedfs_data:
